/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JEmpresa.java
 *
 * Created on 14/05/2010, 13:04:01
 */

package br.com.cadma;

import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vitiazze
 */
public class JEmpresa extends javax.swing.JFrame {

    /** Creates new form JEmpresa */
    public JEmpresa() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        buscarjButton = new javax.swing.JButton();
        novojButton = new javax.swing.JButton();
        editarjButton = new javax.swing.JButton();
        salvarjButton = new javax.swing.JButton();
        alterarjButton = new javax.swing.JButton();
        excluirjButton = new javax.swing.JButton();
        sairjButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradeEmpresajTable = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        razaosocialjTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        codEmpresajSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        cnpjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        inscEstadualjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        enderecojTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bairrojTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cidadejTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        numerojTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ufjComboBox = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        telefonejFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        emailjTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        homePagejTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(JEmpresa.class);
        buscarjButton.setIcon(resourceMap.getIcon("buscarjButton.icon")); // NOI18N
        buscarjButton.setText(resourceMap.getString("buscarjButton.text")); // NOI18N
        buscarjButton.setFocusable(false);
        buscarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscarjButton.setName("buscarjButton"); // NOI18N
        buscarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(buscarjButton);

        novojButton.setIcon(resourceMap.getIcon("novojButton.icon")); // NOI18N
        novojButton.setText(resourceMap.getString("novojButton.text")); // NOI18N
        novojButton.setFocusable(false);
        novojButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        novojButton.setName("novojButton"); // NOI18N
        novojButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        novojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novojButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(novojButton);

        editarjButton.setIcon(resourceMap.getIcon("editarjButton.icon")); // NOI18N
        editarjButton.setText(resourceMap.getString("editarjButton.text")); // NOI18N
        editarjButton.setFocusable(false);
        editarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarjButton.setName("editarjButton"); // NOI18N
        editarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(editarjButton);

        salvarjButton.setIcon(resourceMap.getIcon("salvarjButton.icon")); // NOI18N
        salvarjButton.setText(resourceMap.getString("salvarjButton.text")); // NOI18N
        salvarjButton.setFocusable(false);
        salvarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarjButton.setName("salvarjButton"); // NOI18N
        salvarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(salvarjButton);

        alterarjButton.setIcon(resourceMap.getIcon("alterarjButton.icon")); // NOI18N
        alterarjButton.setText(resourceMap.getString("alterarjButton.text")); // NOI18N
        alterarjButton.setFocusable(false);
        alterarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alterarjButton.setName("alterarjButton"); // NOI18N
        alterarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alterarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(alterarjButton);

        excluirjButton.setIcon(resourceMap.getIcon("excluirjButton.icon")); // NOI18N
        excluirjButton.setText(resourceMap.getString("excluirjButton.text")); // NOI18N
        excluirjButton.setFocusable(false);
        excluirjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        excluirjButton.setName("excluirjButton"); // NOI18N
        excluirjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        excluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(excluirjButton);

        sairjButton.setIcon(resourceMap.getIcon("sairjButton.icon")); // NOI18N
        sairjButton.setText(resourceMap.getString("sairjButton.text")); // NOI18N
        sairjButton.setFocusable(false);
        sairjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sairjButton.setName("sairjButton"); // NOI18N
        sairjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sairjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(sairjButton);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), resourceMap.getColor("jPanel1.border.titleColor"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        gradeEmpresajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Empresa", "Endereço", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        gradeEmpresajTable.setName("gradeEmpresajTable"); // NOI18N
        gradeEmpresajTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradeEmpresajTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gradeEmpresajTable);
        gradeEmpresajTable.getColumnModel().getColumn(0).setMinWidth(50);
        gradeEmpresajTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        gradeEmpresajTable.getColumnModel().getColumn(0).setMaxWidth(50);
        gradeEmpresajTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("gradeEmpresajTable.columnModel.title0")); // NOI18N
        gradeEmpresajTable.getColumnModel().getColumn(1).setMinWidth(200);
        gradeEmpresajTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        gradeEmpresajTable.getColumnModel().getColumn(1).setMaxWidth(200);
        gradeEmpresajTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("gradeEmpresajTable.columnModel.title1")); // NOI18N
        gradeEmpresajTable.getColumnModel().getColumn(2).setMinWidth(300);
        gradeEmpresajTable.getColumnModel().getColumn(2).setPreferredWidth(300);
        gradeEmpresajTable.getColumnModel().getColumn(2).setMaxWidth(300);
        gradeEmpresajTable.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("gradeEmpresajTable.columnModel.title2")); // NOI18N
        gradeEmpresajTable.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("gradeEmpresajTable.columnModel.title3")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        razaosocialjTextField.setText(resourceMap.getString("razaosocialjTextField.text")); // NOI18N
        razaosocialjTextField.setName("razaosocialjTextField"); // NOI18N
        razaosocialjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                razaosocialjTextFieldKeyReleased(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        codEmpresajSpinner.setName("codEmpresajSpinner"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        try {
            cnpjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cnpjFormattedTextField.setName("cnpjFormattedTextField"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        inscEstadualjTextField.setText(resourceMap.getString("inscEstadualjTextField.text")); // NOI18N
        inscEstadualjTextField.setName("inscEstadualjTextField"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        enderecojTextField.setText(resourceMap.getString("enderecojTextField.text")); // NOI18N
        enderecojTextField.setName("enderecojTextField"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        bairrojTextField.setText(resourceMap.getString("bairrojTextField.text")); // NOI18N
        bairrojTextField.setName("bairrojTextField"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        cidadejTextField.setText(resourceMap.getString("cidadejTextField.text")); // NOI18N
        cidadejTextField.setName("cidadejTextField"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        numerojTextField.setText(resourceMap.getString("numerojTextField.text")); // NOI18N
        numerojTextField.setName("numerojTextField"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        ufjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        ufjComboBox.setName("ufjComboBox"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        try {
            telefonejFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefonejFormattedTextField.setName("telefonejFormattedTextField"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        emailjTextField.setText(resourceMap.getString("emailjTextField.text")); // NOI18N
        emailjTextField.setName("emailjTextField"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        homePagejTextField.setText(resourceMap.getString("homePagejTextField.text")); // NOI18N
        homePagejTextField.setName("homePagejTextField"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(155, 155, 155)
                        .addComponent(jLabel3)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(codEmpresajSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(razaosocialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cnpjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(inscEstadualjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(173, 173, 173)
                        .addComponent(jLabel6)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel7)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel8)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(enderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ufjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel11)
                        .addGap(218, 218, 218)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(telefonejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(homePagejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(codEmpresajSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(razaosocialjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnpjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscEstadualjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)))
                    .addComponent(ufjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefonejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homePagejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public ClassConecta conexao = new ClassConecta();

public int codEmpresa;

      public void getGrandeEmpresa() throws ParseException{
       //Consultar pedidos
        Empresa oEmpresa = new Empresa();

        if ( razaosocialjTextField.getText().length() > 0 ){
            oEmpresa.setEmpresa(razaosocialjTextField.getText()+"%");
        }

        ResultSet resultSet = null;

        String[] colunasTabela = new String[]{"Código", "Empresa", "Endereço", "Telefone"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {

            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        gradeEmpresajTable.setModel(modeloTabela);
        gradeEmpresajTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        gradeEmpresajTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        gradeEmpresajTable.getColumnModel().getColumn(2).setPreferredWidth(300);



try {
            resultSet = oEmpresa.getConsultar(conexao);
            if (resultSet.getRow() == 1){
             resultSet.first();
            }


        } catch (SQLException ex) {
            Logger.getLogger(JEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {

            while (resultSet.next()) {

                modeloTabela.addRow(new String[]{
                    Funcoes.getCodigoFormat(resultSet.getInt("codEmpresa")),
                    resultSet.getString("empresa"),
                    resultSet.getString("endereco"),
                    resultSet.getString("telefone"),
                });

            }

        } catch (SQLException ex) {
            Logger.getLogger(JEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }

           }

    public void getFieldEmpresa(int codEmpresa) throws ParseException{
        
        Empresa oEmpresa = new Empresa();
        ResultSet rs = null;
        oEmpresa.setCodEmpresa(codEmpresa);

        try {
            rs = oEmpresa.getConsultar(conexao);
            rs.next();

            //Pegar campos
            razaosocialjTextField.setText(rs.getString("empresa"));
            codEmpresajSpinner.setValue(rs.getInt("codEmpresa"));
            cnpjFormattedTextField.setText(rs.getString("cnpj"));
            inscEstadualjTextField.setText(rs.getString("insEstadual"));
            enderecojTextField.setText(rs.getString("endereco"));
            bairrojTextField.setText(rs.getString("bairro"));
            cidadejTextField.setText(rs.getString("cidade"));
            numerojTextField.setText(rs.getString("numero"));
            ufjComboBox.setSelectedItem(rs.getString("uf"));
            telefonejFormattedTextField.setText(rs.getString("telefone"));
            emailjTextField.setText(rs.getString("email"));
            homePagejTextField.setText(rs.getString("homePage"));
            inscEstadualjTextField.setText(rs.getString("insEstadual"));

        } catch (SQLException ex) {
            Logger.getLogger(Produtos.class.getName()).log(Level.SEVERE, null, ex);
        }



    }


    private void sairjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairjButtonActionPerformed
        // TODO add your handling code here:
        //Feche o formulário
        this.dispose();
    }//GEN-LAST:event_sairjButtonActionPerformed

    private void buscarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarjButtonActionPerformed
        try {
            // TODO add your handling code here:
            getGrandeEmpresa();
        } catch (ParseException ex) {
            Logger.getLogger(JEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
        novojButton.setEnabled(true);
        alterarjButton.setEnabled(false);
        editarjButton.setEnabled(true);
        excluirjButton.setEnabled(false);
        buscarjButton.setEnabled(true);
        salvarjButton.setEnabled(false);
        codEmpresajSpinner.setEnabled(false);

        
    }//GEN-LAST:event_buscarjButtonActionPerformed

    private void novojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novojButtonActionPerformed
        try {
            // TODO add your handling code here:
            novojButton.setEnabled(false);
            alterarjButton.setEnabled(false);
            editarjButton.setEnabled(false);
            excluirjButton.setEnabled(false);
            buscarjButton.setEnabled(true);
            salvarjButton.setEnabled(true);
            codEmpresajSpinner.setEnabled(false);
            
            conexao.con.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(JEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }

            Funcoes.limpaCampos(jPanel1);
            razaosocialjTextField.setText("");
            cnpjFormattedTextField.setText("");
            inscEstadualjTextField.setText("");
            enderecojTextField.setText("");
            numerojTextField.setText("");
            bairrojTextField.setText("");
            cidadejTextField.setText("");
            telefonejFormattedTextField.setText("");
            emailjTextField.setText("");
            homePagejTextField.setText("");
            ufjComboBox.setSelectedItem("AC");
            codEmpresajSpinner.setValue(0);


    }//GEN-LAST:event_novojButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        try {
            // TODO add your handling code here:
            novojButton.setEnabled(false);
            salvarjButton.setEnabled(false);
            editarjButton.setEnabled(false);
            alterarjButton.setEnabled(true);
            excluirjButton.setEnabled(true);
            conexao.con.setAutoCommit(false);

        } catch (SQLException ex) {
            Logger.getLogger(JEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_editarjButtonActionPerformed

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        Empresa oEmpresa = new Empresa();

        if (razaosocialjTextField.getText().equals("") || enderecojTextField.getText().equals("") || numerojTextField.getText().equals("") ||
            bairrojTextField.getText().equals("")) {


            JOptionPane.showMessageDialog(null, "Preencha os campos: Razao Social, Endereço, numero e Bairro.", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
        }else{try {
                {
                    salvarjButton.setEnabled(false);
                    alterarjButton.setEnabled(false);
                    excluirjButton.setEnabled(false);
                    novojButton.setEnabled(true);
                    editarjButton.setEnabled(true);
                    
                    oEmpresa.setEmpresa(razaosocialjTextField.getText());
                    oEmpresa.setCnpj(cnpjFormattedTextField.getText());
                    oEmpresa.setEndereco(enderecojTextField.getText());
                    oEmpresa.setNumero(numerojTextField.getText());
                    oEmpresa.setBairro(bairrojTextField.getText());
                    oEmpresa.setCidade(cidadejTextField.getText());
                    oEmpresa.setUf((String) ufjComboBox.getSelectedItem());
                    oEmpresa.setTelefone(telefonejFormattedTextField.getText());
                    oEmpresa.setEmail(emailjTextField.getText());
                    oEmpresa.setHomePage(homePagejTextField.getText());

                    oEmpresa.setCadastrar(conexao);
                    try {
                        conexao.con.commit();
                        conexao.con.setAutoCommit(true);
                    } catch (SQLException ex) {
                        Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        getGrandeEmpresa();
                    } catch (ParseException ex) {
                        Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }


                Funcoes.limpaCampos(jPanel1);
                razaosocialjTextField.setText("");
                cnpjFormattedTextField.setText("");
                enderecojTextField.setText("");
                numerojTextField.setText("");
                bairrojTextField.setText("");
                homePagejTextField.setText("");
                cidadejTextField.setText("");
                telefonejFormattedTextField.setText("");
                emailjTextField.setText("");
                inscEstadualjTextField.setText("");
                getGrandeEmpresa();
                razaosocialjTextField.grabFocus();
            } catch (ParseException ex) {
                Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


       

    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void alterarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarjButtonActionPerformed
        // TODO add your handling code here:
        alterarjButton.setEnabled(false);
        editarjButton.setEnabled(true);
        excluirjButton.setEnabled(false);
        novojButton.setEnabled(true);

        @SuppressWarnings("LocalVariableHidesMemberVariable")
        int codEmpresa = 0;
        codEmpresa = Integer.parseInt(gradeEmpresajTable.getValueAt(gradeEmpresajTable.getSelectedRow(), 0).toString());

        Empresa oEmpresa = new Empresa();

        oEmpresa.setCodEmpresa(codEmpresa);
        oEmpresa.setEmpresa(razaosocialjTextField.getText());
        oEmpresa.setCnpj(cnpjFormattedTextField.getText());
        oEmpresa.setInsEstadual(inscEstadualjTextField.getText());
        oEmpresa.setEndereco(enderecojTextField.getText());
        oEmpresa.setNumero(numerojTextField.getText());
        oEmpresa.setBairro(bairrojTextField.getText());
        oEmpresa.setCidade(cidadejTextField.getText());
        oEmpresa.setUf((String) ufjComboBox.getSelectedItem());
        oEmpresa.setTelefone(telefonejFormattedTextField.getText());
        oEmpresa.setEmail(emailjTextField.getText());
        oEmpresa.setHomePage(homePagejTextField.getText());
        oEmpresa.setAlterar(conexao);
        try {
            conexao.con.commit();
            conexao.con.setAutoCommit(true);
        } catch (SQLException ex) {
            Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
        razaosocialjTextField.setText("");
        cnpjFormattedTextField.setText("");
        inscEstadualjTextField.setText("");
        enderecojTextField.setText("");
        numerojTextField.setText("");
        bairrojTextField.setText("");
        cidadejTextField.setText("");
        telefonejFormattedTextField.setText("");
        emailjTextField.setText("");
        homePagejTextField.setText("");
        codEmpresajSpinner.setValue(0);
            getGrandeEmpresa();
        } catch (ParseException ex) {
            Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
        }




    }//GEN-LAST:event_alterarjButtonActionPerformed

    private void excluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButtonActionPerformed
        // TODO add your handling code here:
         Object[] options = {"Sim", "Não"};
        int sd =
                JOptionPane.showOptionDialog(
                null,
                "Deseja realmente EXCLUIR esta Empresa?",
                "Confirmação!",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                options,
                options[0]);

        if (sd != 0) {
            return;
        }

        alterarjButton.setEnabled(false);
        editarjButton.setEnabled(true);
        excluirjButton.setEnabled(false);
        novojButton.setEnabled(true);

         int codigoEmpresa = 0;
        codigoEmpresa = Integer.parseInt(gradeEmpresajTable.getValueAt(gradeEmpresajTable.getSelectedRow(), 0).toString());

        Empresa oEmpresa = new Empresa();
        oEmpresa.setCodEmpresa(codigoEmpresa);
        oEmpresa.setExcluir(conexao);
        try {
            conexao.con.commit();
            conexao.con.setAutoCommit(true);
        } catch (SQLException ex) {
            Logger.getLogger(jFProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
        Funcoes.limpaCampos(jPanel1);
        razaosocialjTextField.setText("");
        cnpjFormattedTextField.setText("");
        inscEstadualjTextField.setText("");
        enderecojTextField.setText("");
        numerojTextField.setText("");
        bairrojTextField.setText("");
        cidadejTextField.setText("");
        telefonejFormattedTextField.setText("");
        emailjTextField.setText("");
        homePagejTextField.setText("");
        codEmpresajSpinner.setValue(0);
            getGrandeEmpresa();
        } catch (ParseException ex) {
            Logger.getLogger(jFProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }




    }//GEN-LAST:event_excluirjButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conexao.conecta();
        buscarjButtonActionPerformed(null);
        razaosocialjTextField.grabFocus();
    }//GEN-LAST:event_formWindowOpened

    private void gradeEmpresajTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeEmpresajTableMouseClicked
        // TODO add your handling code here:
                try {
            // TODO add your handling code here:
            editarjButton.setEnabled(true);
            codEmpresa = Integer.parseInt(gradeEmpresajTable.getValueAt(gradeEmpresajTable.getSelectedRow(), 0).toString());
            if (codEmpresa == 0) {
                return;
            }
            getFieldEmpresa(codEmpresa);
        } catch (ParseException ex) {
            Logger.getLogger(JEmpresa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gradeEmpresajTableMouseClicked

    private void razaosocialjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_razaosocialjTextFieldKeyReleased
        // TODO add your handling code here:
                if (!alterarjButton.isEnabled()){
            try {
                Empresa oEmpresa = new Empresa();
                oEmpresa.setEmpresa(razaosocialjTextField.getText());
                ResultSet rs = null;
                rs = oEmpresa.getConsultar(conexao);
                getGrandeEmpresa();
            } catch (ParseException ex) {
                Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
                    }
    }



    }//GEN-LAST:event_razaosocialjTextFieldKeyReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarjButton;
    private javax.swing.JTextField bairrojTextField;
    private javax.swing.JButton buscarjButton;
    private javax.swing.JTextField cidadejTextField;
    private javax.swing.JFormattedTextField cnpjFormattedTextField;
    private javax.swing.JSpinner codEmpresajSpinner;
    private javax.swing.JButton editarjButton;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JTextField enderecojTextField;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JTable gradeEmpresajTable;
    private javax.swing.JTextField homePagejTextField;
    private javax.swing.JTextField inscEstadualjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton novojButton;
    private javax.swing.JTextField numerojTextField;
    private javax.swing.JTextField razaosocialjTextField;
    private javax.swing.JButton sairjButton;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JFormattedTextField telefonejFormattedTextField;
    private javax.swing.JComboBox ufjComboBox;
    // End of variables declaration//GEN-END:variables

}
