/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jFClientes.java
 *
 * Created on 21/05/2010, 13:06:20
 */

package br.com.cadma;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Vitiazze
 */
public class jFClientes extends javax.swing.JFrame {

    /** Creates new form jFClientes */
    public jFClientes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")



    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        buscarjButton = new javax.swing.JButton();
        novojButton = new javax.swing.JButton();
        editarjButton = new javax.swing.JButton();
        salvarjButton = new javax.swing.JButton();
        alterarjButton = new javax.swing.JButton();
        excluirjButton = new javax.swing.JButton();
        sairjButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradeClientesjTable = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        nomejTextField = new javax.swing.JTextField();
        codigojSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tipoClientejComboBox = new javax.swing.JComboBox();
        cpfjLabel = new javax.swing.JLabel();
        cpfCnpjFormattedTextField = new javax.swing.JFormattedTextField();
        rgjLabel = new javax.swing.JLabel();
        rgInscricaoEstadualjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        enderecojTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        numerojTextField = new javax.swing.JTextField();
        bairrojTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        complementojTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cidadejTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ufjComboBox = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        telefonejFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        emailjTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(jFClientes.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        buscarjButton.setIcon(resourceMap.getIcon("buscarjButton.icon")); // NOI18N
        buscarjButton.setText(resourceMap.getString("buscarjButton.text")); // NOI18N
        buscarjButton.setFocusable(false);
        buscarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscarjButton.setName("buscarjButton"); // NOI18N
        buscarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(buscarjButton);

        novojButton.setIcon(resourceMap.getIcon("novojButton.icon")); // NOI18N
        novojButton.setText(resourceMap.getString("novojButton.text")); // NOI18N
        novojButton.setFocusable(false);
        novojButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        novojButton.setName("novojButton"); // NOI18N
        novojButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        novojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novojButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(novojButton);

        editarjButton.setIcon(resourceMap.getIcon("editarjButton.icon")); // NOI18N
        editarjButton.setText(resourceMap.getString("editarjButton.text")); // NOI18N
        editarjButton.setFocusable(false);
        editarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarjButton.setName("editarjButton"); // NOI18N
        editarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(editarjButton);

        salvarjButton.setIcon(resourceMap.getIcon("salvarjButton.icon")); // NOI18N
        salvarjButton.setText(resourceMap.getString("salvarjButton.text")); // NOI18N
        salvarjButton.setFocusable(false);
        salvarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarjButton.setName("salvarjButton"); // NOI18N
        salvarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(salvarjButton);

        alterarjButton.setIcon(resourceMap.getIcon("alterarjButton.icon")); // NOI18N
        alterarjButton.setText(resourceMap.getString("alterarjButton.text")); // NOI18N
        alterarjButton.setToolTipText(resourceMap.getString("alterarjButton.toolTipText")); // NOI18N
        alterarjButton.setFocusable(false);
        alterarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alterarjButton.setName("alterarjButton"); // NOI18N
        alterarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alterarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(alterarjButton);

        excluirjButton.setIcon(resourceMap.getIcon("excluirjButton.icon")); // NOI18N
        excluirjButton.setText(resourceMap.getString("excluirjButton.text")); // NOI18N
        excluirjButton.setFocusable(false);
        excluirjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        excluirjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        excluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(excluirjButton);

        sairjButton.setIcon(resourceMap.getIcon("sairjButton.icon")); // NOI18N
        sairjButton.setText(resourceMap.getString("sairjButton.text")); // NOI18N
        sairjButton.setFocusable(false);
        sairjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sairjButton.setName("sairjButton"); // NOI18N
        sairjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sairjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(sairjButton);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), 0, 0, resourceMap.getFont("jPanel1.border.titleFont"), resourceMap.getColor("jPanel1.border.titleColor"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        gradeClientesjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cliente", "Endereço", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        gradeClientesjTable.setName("gradeClientesjTable"); // NOI18N
        gradeClientesjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradeClientesjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gradeClientesjTable);
        gradeClientesjTable.getColumnModel().getColumn(0).setResizable(false);
        gradeClientesjTable.getColumnModel().getColumn(0).setPreferredWidth(90);
        gradeClientesjTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("gradeClientesjTable.columnModel.title0")); // NOI18N
        gradeClientesjTable.getColumnModel().getColumn(1).setResizable(false);
        gradeClientesjTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        gradeClientesjTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("gradeClientesjTable.columnModel.title1")); // NOI18N
        gradeClientesjTable.getColumnModel().getColumn(2).setResizable(false);
        gradeClientesjTable.getColumnModel().getColumn(2).setPreferredWidth(200);
        gradeClientesjTable.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("gradeClientesjTable.columnModel.title2")); // NOI18N
        gradeClientesjTable.getColumnModel().getColumn(3).setResizable(false);
        gradeClientesjTable.getColumnModel().getColumn(3).setPreferredWidth(150);
        gradeClientesjTable.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("gradeClientesjTable.columnModel.title3")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setName("jPanel2"); // NOI18N

        nomejTextField.setText(resourceMap.getString("nomejTextField.text")); // NOI18N
        nomejTextField.setName("nomejTextField"); // NOI18N
        nomejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomejTextFieldKeyReleased(evt);
            }
        });

        codigojSpinner.setFont(resourceMap.getFont("codigojSpinner.font")); // NOI18N
        codigojSpinner.setName("codigojSpinner"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        tipoClientejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Física", "Jurídica" }));
        tipoClientejComboBox.setName("tipoClientejComboBox"); // NOI18N
        tipoClientejComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoClientejComboBoxItemStateChanged(evt);
            }
        });
        tipoClientejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoClientejComboBoxActionPerformed(evt);
            }
        });

        cpfjLabel.setText(resourceMap.getString("cpfjLabel.text")); // NOI18N
        cpfjLabel.setName("cpfjLabel"); // NOI18N

        try {
            cpfCnpjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfCnpjFormattedTextField.setName("cpfCnpjFormattedTextField"); // NOI18N
        cpfCnpjFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfCnpjFormattedTextFieldActionPerformed(evt);
            }
        });

        rgjLabel.setText(resourceMap.getString("rgjLabel.text")); // NOI18N
        rgjLabel.setName("rgjLabel"); // NOI18N

        rgInscricaoEstadualjTextField.setText(resourceMap.getString("rgInscricaoEstadualjTextField.text")); // NOI18N
        rgInscricaoEstadualjTextField.setName("rgInscricaoEstadualjTextField"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        enderecojTextField.setText(resourceMap.getString("enderecojTextField.text")); // NOI18N
        enderecojTextField.setName("enderecojTextField"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        numerojTextField.setText(resourceMap.getString("numerojTextField.text")); // NOI18N
        numerojTextField.setName("numerojTextField"); // NOI18N

        bairrojTextField.setText(resourceMap.getString("bairrojTextField.text")); // NOI18N
        bairrojTextField.setName("bairrojTextField"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        complementojTextField.setText(resourceMap.getString("complementojTextField.text")); // NOI18N
        complementojTextField.setName("complementojTextField"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        cidadejTextField.setText(resourceMap.getString("cidadejTextField.text")); // NOI18N
        cidadejTextField.setName("cidadejTextField"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        ufjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        ufjComboBox.setName("ufjComboBox"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        try {
            telefonejFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefonejFormattedTextField.setName("telefonejFormattedTextField"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        emailjTextField.setText(resourceMap.getString("emailjTextField.text")); // NOI18N
        emailjTextField.setName("emailjTextField"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(codigojSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel2))
                            .addComponent(jLabel6)
                            .addComponent(enderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(numerojTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(tipoClientejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ufjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(117, 117, 117)
                                .addComponent(jLabel11)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefonejFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jLabel12))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(cpfCnpjFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(cpfjLabel)
                            .addComponent(bairrojTextField))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(rgInscricaoEstadualjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(rgjLabel)
                            .addComponent(complementojTextField)))
                    .addComponent(jLabel13)
                    .addComponent(emailjTextField))
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(cpfjLabel)
                    .addComponent(rgjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigojSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoClientejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfCnpjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rgInscricaoEstadualjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(complementojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ufjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, 0, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int codCliente;

    MaskFormatter formato = null;






        public ClassConecta conexao = new ClassConecta();

    public void getGradeSituacao() throws ParseException{
       //Consultar pedidos
        Clientes oCliente = new Clientes();
        if ( nomejTextField.getText().length() > 0 ){
            oCliente.setNome(nomejTextField.getText()+"%");
        }



        ResultSet resultSet = null;

        String[] colunasTabela = new String[]{"Código", "Cliente", "Endereço", "Telefone"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {

            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        gradeClientesjTable.setModel(modeloTabela);
        gradeClientesjTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        gradeClientesjTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        gradeClientesjTable.getColumnModel().getColumn(2).setPreferredWidth(250);
        gradeClientesjTable.getColumnModel().getColumn(3).setPreferredWidth(70);


try {
            resultSet = oCliente.getConsultar(conexao);

        } catch (SQLException ex) {
            Logger.getLogger(jFProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {

            while (resultSet.next()) {

                modeloTabela.addRow(new String[]{
                    Funcoes.getCodigoFormat(resultSet.getInt("codCliente")),
                    resultSet.getString("nome"),
                    resultSet.getString("endereco"),
                    resultSet.getString("telefone")
                });

            }

        } catch (SQLException ex) {
            Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

           }

    private void getField() throws SQLException{
        Clientes oCliente = new Clientes();
        oCliente.setCodCliente(codCliente);

        ResultSet rs = null;
        rs = oCliente.getConsultar(conexao);

        rs.first();


        codigojSpinner.setValue(rs.getInt("codCliente"));
        nomejTextField.setText(rs.getString("nome"));
        tipoClientejComboBox.setSelectedItem(rs.getString("tipoCliente"));
        cpfCnpjFormattedTextField.setText(rs.getString("cpfCnpj"));
        rgInscricaoEstadualjTextField.setText(rs.getString("rgInsEstadual"));
        enderecojTextField.setText(rs.getString("endereco"));
        numerojTextField.setText(rs.getString("numero"));
        bairrojTextField.setText(rs.getString("bairro"));
        complementojTextField.setText(rs.getString("complemento"));
        cidadejTextField.setText(rs.getString("cidade"));
        ufjComboBox.setSelectedItem(rs.getString("uf"));
        telefonejFormattedTextField.setText(rs.getString("telefone"));
        emailjTextField.setText(rs.getString("email"));






    }

    private void sairjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairjButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_sairjButtonActionPerformed

    private void novojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novojButtonActionPerformed
        // TODO add your handling code here:
        novojButton.setEnabled(false);
        alterarjButton.setEnabled(false);
        editarjButton.setEnabled(false);
        excluirjButton.setEnabled(false);
        buscarjButton.setEnabled(true);
        salvarjButton.setEnabled(true);
        codigojSpinner.setEnabled(false);
        nomejTextField.grabFocus();


        try {
            conexao.con.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
        }


        Funcoes.limpaCampos(jPanel1);
        nomejTextField.setText("");
        cpfCnpjFormattedTextField.setText("");
        rgInscricaoEstadualjTextField.setText("");
        enderecojTextField.setText("");
        numerojTextField.setText("");
        bairrojTextField.setText("");
        complementojTextField.setText("");
        cidadejTextField.setText("");
        telefonejFormattedTextField.setText("");
        emailjTextField.setText("");

    }//GEN-LAST:event_novojButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        novojButton.setEnabled(true);
        alterarjButton.setEnabled(false);
        editarjButton.setEnabled(false);
        excluirjButton.setEnabled(false);
        buscarjButton.setEnabled(true);
        salvarjButton.setEnabled(false);
        nomejTextField.grabFocus();


        conexao.conecta();
        buscarjButtonActionPerformed(null);
    }//GEN-LAST:event_formWindowOpened

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:
        Clientes oCliente = new Clientes();

        if (nomejTextField.getText().equals("") || enderecojTextField.getText().equals("") || numerojTextField.getText().equals("") || 
            bairrojTextField.getText().equals("")) {

            
            JOptionPane.showMessageDialog(null, "Preencha os campos: nome, Endereço, numero e Bairro.", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
        }else{try {
                {
                    salvarjButton.setEnabled(false);
                    alterarjButton.setEnabled(false);
                    excluirjButton.setEnabled(false);
                    novojButton.setEnabled(true);
                    editarjButton.setEnabled(true);
                    oCliente.setNome(nomejTextField.getText());
                    oCliente.setTipoCliente((String) tipoClientejComboBox.getSelectedItem());
                    oCliente.setCpfCnpj(cpfCnpjFormattedTextField.getText());
                    oCliente.setTipoCliente((String) tipoClientejComboBox.getSelectedItem());
                    oCliente.setEndereco(enderecojTextField.getText());
                    oCliente.setNumero(numerojTextField.getText());
                    oCliente.setBairro(bairrojTextField.getText());
                    oCliente.setComplemento(complementojTextField.getText());
                    oCliente.setCidade(cidadejTextField.getText());
                    oCliente.setUf((String) ufjComboBox.getSelectedItem());
                    oCliente.setTelefone(telefonejFormattedTextField.getText());
                    oCliente.setEmail(emailjTextField.getText());
                    oCliente.setCadastrar(conexao);
                    try {
                        conexao.con.commit();
                        conexao.con.setAutoCommit(true);
                    } catch (SQLException ex) {
                        Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        getGradeSituacao();
                    } catch (ParseException ex) {
                        Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                
                Funcoes.limpaCampos(jPanel1);
                nomejTextField.setText("");
                cpfCnpjFormattedTextField.setText("");
                rgInscricaoEstadualjTextField.setText("");
                enderecojTextField.setText("");
                numerojTextField.setText("");
                bairrojTextField.setText("");
                complementojTextField.setText("");
                cidadejTextField.setText("");
                telefonejFormattedTextField.setText("");
                emailjTextField.setText("");
                getGradeSituacao();
            } catch (ParseException ex) {
                Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void buscarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarjButtonActionPerformed
        try {
            // TODO add your handling code here:
            getGradeSituacao();
        } catch (ParseException ex) {
            Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buscarjButtonActionPerformed

    private void tipoClientejComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoClientejComboBoxItemStateChanged
        // TODO add your handling code here:
        

        if (tipoClientejComboBox.getSelectedItem().equals("Física")) {
            try {
                formato = new MaskFormatter("###.###.###-##");
                cpfjLabel.setText("CPF");
                rgjLabel.setText("RG");
            } catch (ParseException ex) {
                Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
            }

        }else{
            try {
                formato = new MaskFormatter("##.###.###/####-##");
                cpfjLabel.setText("CNPJ");
                rgjLabel.setText("Insc. Estadual");
            } catch (ParseException ex) {
                Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        DefaultFormatterFactory fator = new DefaultFormatterFactory(formato);
        cpfCnpjFormattedTextField.setFormatterFactory(fator);



    }//GEN-LAST:event_tipoClientejComboBoxItemStateChanged

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        novojButton.setEnabled(false);
        salvarjButton.setEnabled(false);
        editarjButton.setEnabled(false);
        alterarjButton.setEnabled(true);
        excluirjButton.setEnabled(true);
        try {
            conexao.con.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_editarjButtonActionPerformed

    private void alterarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarjButtonActionPerformed
        // TODO add your handling code here:
        alterarjButton.setEnabled(false);
        editarjButton.setEnabled(true);
        excluirjButton.setEnabled(false);
        novojButton.setEnabled(true);
        
        
        int codClientes = 0;
        codClientes = Integer.parseInt(gradeClientesjTable.getValueAt(gradeClientesjTable.getSelectedRow(), 0).toString());

        Clientes oCliente = new Clientes();
        oCliente.setCodCliente(codClientes);
        oCliente.setNome(nomejTextField.getText());
        oCliente.setTipoCliente((String) tipoClientejComboBox.getSelectedItem());
        oCliente.setCpfCnpj(cpfCnpjFormattedTextField.getText());
        oCliente.setRgInsEstadual(rgInscricaoEstadualjTextField.getText());
        oCliente.setEndereco(enderecojTextField.getText());
        oCliente.setNumero(numerojTextField.getText());
        oCliente.setBairro(bairrojTextField.getText());
        oCliente.setComplemento(complementojTextField.getText());
        oCliente.setCidade(cidadejTextField.getText());
        oCliente.setUf((String) ufjComboBox.getSelectedItem()); 
        oCliente.setTelefone(telefonejFormattedTextField.getText());
        oCliente.setEmail(emailjTextField.getText());
        oCliente.setAlterar(conexao);
        try {
            conexao.con.commit();
            conexao.con.setAutoCommit(true);
        } catch (SQLException ex) {
            Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            getGradeSituacao();
        } catch (ParseException ex) {
            Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_alterarjButtonActionPerformed

    private void excluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButtonActionPerformed
        // TODO add your handling code here:
         Object[] options = {"Sim", "Não"};
        int sd =
                JOptionPane.showOptionDialog(
                null,
                "Deseja realmente EXCLUIR este CLIENTE?",
                "Confirmação!",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                options,
                options[0]);

        if (sd != 0) {
            return;
        }

        alterarjButton.setEnabled(false);
        editarjButton.setEnabled(true);
        excluirjButton.setEnabled(false);
        novojButton.setEnabled(true);

         int codSituacao = 0;
        codSituacao = Integer.parseInt(gradeClientesjTable.getValueAt(gradeClientesjTable.getSelectedRow(), 0).toString());

        Clientes oCliente = new Clientes();
        oCliente.setCodCliente(codSituacao);
        oCliente.setExcluir(conexao);
        try {
            conexao.con.commit();
            conexao.con.setAutoCommit(true);
        } catch (SQLException ex) {
            Logger.getLogger(jFProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            getGradeSituacao();
        } catch (ParseException ex) {
            Logger.getLogger(jFProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }

        Funcoes.limpaCampos(jPanel1);
        nomejTextField.setText("");
        cpfCnpjFormattedTextField.setText("");
        rgInscricaoEstadualjTextField.setText("");
        enderecojTextField.setText("");
        numerojTextField.setText("");
        bairrojTextField.setText("");
        complementojTextField.setText("");
        cidadejTextField.setText("");
        telefonejFormattedTextField.setText("");
        emailjTextField.setText("");

    }//GEN-LAST:event_excluirjButtonActionPerformed

       
    private void gradeClientesjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeClientesjTableMouseClicked
        try {
            // TODO add your handling code here:
            editarjButton.setEnabled(true);
            codCliente = Integer.parseInt(gradeClientesjTable.getValueAt(gradeClientesjTable.getSelectedRow(), 0).toString());
            if (codCliente == 0) {
                return;
            }
            getField();
        } catch (SQLException ex) {
            Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gradeClientesjTableMouseClicked

    private void nomejTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomejTextFieldKeyReleased
        // TODO add your handling code here:
        if (!alterarjButton.isEnabled()){
            try {
                Clientes oCliente = new Clientes();
                oCliente.setNome(nomejTextField.getText());
                ResultSet rs = null;
                rs = oCliente.getConsultar(conexao);
                getGradeSituacao();
            } catch (ParseException ex) {
                Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
            }



    }
    }//GEN-LAST:event_nomejTextFieldKeyReleased

    private void tipoClientejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoClientejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoClientejComboBoxActionPerformed

    private void cpfCnpjFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfCnpjFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfCnpjFormattedTextFieldActionPerformed





    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarjButton;
    private javax.swing.JTextField bairrojTextField;
    private javax.swing.JButton buscarjButton;
    private javax.swing.JTextField cidadejTextField;
    private javax.swing.JSpinner codigojSpinner;
    private javax.swing.JTextField complementojTextField;
    private javax.swing.JFormattedTextField cpfCnpjFormattedTextField;
    private javax.swing.JLabel cpfjLabel;
    private javax.swing.JButton editarjButton;
    private javax.swing.JTextField emailjTextField;
    private javax.swing.JTextField enderecojTextField;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JTable gradeClientesjTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JButton novojButton;
    private javax.swing.JTextField numerojTextField;
    private javax.swing.JTextField rgInscricaoEstadualjTextField;
    private javax.swing.JLabel rgjLabel;
    private javax.swing.JButton sairjButton;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JFormattedTextField telefonejFormattedTextField;
    private javax.swing.JComboBox tipoClientejComboBox;
    private javax.swing.JComboBox ufjComboBox;
    // End of variables declaration//GEN-END:variables

}
