/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jFFuncionarios.java
 *
 * Created on 21/05/2010, 19:50:19
 */

package br.com.cadma;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vitiazze
 */
public class jFFuncionarios extends javax.swing.JFrame {

    /** Creates new form jFFuncionarios */
    public jFFuncionarios() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

       public ClassConecta conexao = new ClassConecta();
    
        public void getGradeSituacao() throws ParseException{
       //Consultar pedidos
        Funcionarios oFuncionario = new Funcionarios();

        ResultSet resultSet = null;

        String[] colunasTabela = new String[]{"Código", "Funcionario", "Cargo", "Telefone", "Usuário"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela) {

            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        gradeFuncjTable.setModel(modeloTabela);
        gradeFuncjTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        gradeFuncjTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        gradeFuncjTable.getColumnModel().getColumn(2).setPreferredWidth(250);
        gradeFuncjTable.getColumnModel().getColumn(3).setPreferredWidth(70);
        gradeFuncjTable.getColumnModel().getColumn(4).setPreferredWidth(70);


try {
            resultSet = oFuncionario.getConsultar(conexao);
            if (resultSet.getRow() == 1){
             resultSet.first();
            }


        } catch (SQLException ex) {
            Logger.getLogger(jFProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {

            while (resultSet.next()) {

                modeloTabela.addRow(new String[]{
                    Funcoes.getCodigoFormat(resultSet.getInt("codFuncionario")),
                    resultSet.getString("funcionario"),
                    resultSet.getString("cargo"),
                    resultSet.getString("telefone"),
                    resultSet.getString("usuario")
                });

            }

        } catch (SQLException ex) {
            Logger.getLogger(jFProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }

           }

    public void getFieldClientes(int codClientes) throws ParseException{
        //Buscar produto
        Clientes oCliente = new Clientes();
        ResultSet rs = null;
        oCliente.setCodCliente(codClientes);

        try {
            rs = oCliente.getConsultar(conexao);
            rs.next();

            //Pegar campos
            funcionariojTextField.setText(rs.getString("funcionario"));
            cargojTextField.setText(rs.getString("cargo"));
            telefonejFormattedTextField.setText(rs.getString("telefone"));
            usuariojTextField.setText(rs.getString("usuario"));


        } catch (SQLException ex) {
            Logger.getLogger(Produtos.class.getName()).log(Level.SEVERE, null, ex);
        }



    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        buscarjButton = new javax.swing.JButton();
        novojButton = new javax.swing.JButton();
        editarjButton = new javax.swing.JButton();
        salvarjButton = new javax.swing.JButton();
        alterarjButton = new javax.swing.JButton();
        excluirjButton = new javax.swing.JButton();
        sairjButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradeFuncjTable = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codigojSpinner = new javax.swing.JSpinner();
        funcionariojTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cpfjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        rgjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        enderecojTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        numerojTextField = new javax.swing.JTextField();
        bairrojTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cidadejTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        complementojTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ufjComboBox = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        telefonejFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        cargojTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        usuariojTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        senhajPasswordField = new javax.swing.JPasswordField();
        resenhajPasswordField = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        tipoUserjComboBox = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(jFFuncionarios.class);
        jToolBar1.setFont(resourceMap.getFont("jToolBar1.font")); // NOI18N
        jToolBar1.setName("jToolBar1"); // NOI18N

        buscarjButton.setIcon(resourceMap.getIcon("buscarjButton.icon")); // NOI18N
        buscarjButton.setText(resourceMap.getString("buscarjButton.text")); // NOI18N
        buscarjButton.setFocusable(false);
        buscarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscarjButton.setName("buscarjButton"); // NOI18N
        buscarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(buscarjButton);

        novojButton.setIcon(resourceMap.getIcon("novojButton.icon")); // NOI18N
        novojButton.setText(resourceMap.getString("novojButton.text")); // NOI18N
        novojButton.setFocusable(false);
        novojButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        novojButton.setName("novojButton"); // NOI18N
        novojButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        novojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novojButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(novojButton);

        editarjButton.setIcon(resourceMap.getIcon("editarjButton.icon")); // NOI18N
        editarjButton.setText(resourceMap.getString("editarjButton.text")); // NOI18N
        editarjButton.setFocusable(false);
        editarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarjButton.setName("editarjButton"); // NOI18N
        editarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(editarjButton);

        salvarjButton.setIcon(resourceMap.getIcon("salvarjButton.icon")); // NOI18N
        salvarjButton.setText(resourceMap.getString("salvarjButton.text")); // NOI18N
        salvarjButton.setFocusable(false);
        salvarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarjButton.setName("salvarjButton"); // NOI18N
        salvarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(salvarjButton);

        alterarjButton.setIcon(resourceMap.getIcon("alterarjButton.icon")); // NOI18N
        alterarjButton.setText(resourceMap.getString("alterarjButton.text")); // NOI18N
        alterarjButton.setFocusable(false);
        alterarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alterarjButton.setName("alterarjButton"); // NOI18N
        alterarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alterarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(alterarjButton);

        excluirjButton.setIcon(resourceMap.getIcon("excluirjButton.icon")); // NOI18N
        excluirjButton.setText(resourceMap.getString("excluirjButton.text")); // NOI18N
        excluirjButton.setFocusable(false);
        excluirjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        excluirjButton.setName("excluirjButton"); // NOI18N
        excluirjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        excluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(excluirjButton);

        sairjButton.setIcon(resourceMap.getIcon("sairjButton.icon")); // NOI18N
        sairjButton.setText(resourceMap.getString("sairjButton.text")); // NOI18N
        sairjButton.setFocusable(false);
        sairjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sairjButton.setName("sairjButton"); // NOI18N
        sairjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sairjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairjButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(sairjButton);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), resourceMap.getColor("jPanel1.border.titleColor"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        gradeFuncjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Funcionario", "Cargo", "Telefone", "Usuário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        gradeFuncjTable.setName("gradeFuncjTable"); // NOI18N
        jScrollPane1.setViewportView(gradeFuncjTable);
        gradeFuncjTable.getColumnModel().getColumn(0).setResizable(false);
        gradeFuncjTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        gradeFuncjTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("gradeFuncjTable.columnModel.title0")); // NOI18N
        gradeFuncjTable.getColumnModel().getColumn(1).setResizable(false);
        gradeFuncjTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        gradeFuncjTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("gradeFuncjTable.columnModel.title1")); // NOI18N
        gradeFuncjTable.getColumnModel().getColumn(2).setResizable(false);
        gradeFuncjTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        gradeFuncjTable.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("gradeFuncjTable.columnModel.title2")); // NOI18N
        gradeFuncjTable.getColumnModel().getColumn(3).setResizable(false);
        gradeFuncjTable.getColumnModel().getColumn(3).setPreferredWidth(80);
        gradeFuncjTable.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("gradeFuncjTable.columnModel.title3")); // NOI18N
        gradeFuncjTable.getColumnModel().getColumn(4).setResizable(false);
        gradeFuncjTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        gradeFuncjTable.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("gradeFuncjTable.columnModel.title4")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
        );

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        codigojSpinner.setName("codigojSpinner"); // NOI18N

        funcionariojTextField.setText(resourceMap.getString("funcionariojTextField.text")); // NOI18N
        funcionariojTextField.setName("funcionariojTextField"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        try {
            cpfjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfjFormattedTextField.setName("cpfjFormattedTextField"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        rgjTextField.setText(resourceMap.getString("rgjTextField.text")); // NOI18N
        rgjTextField.setName("rgjTextField"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setName("jLabel5"); // NOI18N

        enderecojTextField.setText(resourceMap.getString("enderecojTextField.text")); // NOI18N
        enderecojTextField.setName("enderecojTextField"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        numerojTextField.setText(resourceMap.getString("numerojTextField.text")); // NOI18N
        numerojTextField.setName("numerojTextField"); // NOI18N

        bairrojTextField.setText(resourceMap.getString("bairrojTextField.text")); // NOI18N
        bairrojTextField.setName("bairrojTextField"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        cidadejTextField.setText(resourceMap.getString("cidadejTextField.text")); // NOI18N
        cidadejTextField.setName("cidadejTextField"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        complementojTextField.setText(resourceMap.getString("complementojTextField.text")); // NOI18N
        complementojTextField.setName("complementojTextField"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        ufjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        ufjComboBox.setName("ufjComboBox"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        try {
            telefonejFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefonejFormattedTextField.setName("telefonejFormattedTextField"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        cargojTextField.setText(resourceMap.getString("cargojTextField.text")); // NOI18N
        cargojTextField.setName("cargojTextField"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        usuariojTextField.setText(resourceMap.getString("usuariojTextField.text")); // NOI18N
        usuariojTextField.setName("usuariojTextField"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        senhajPasswordField.setText(resourceMap.getString("senhajPasswordField.text")); // NOI18N
        senhajPasswordField.setName("senhajPasswordField"); // NOI18N

        resenhajPasswordField.setText(resourceMap.getString("resenhajPasswordField.text")); // NOI18N
        resenhajPasswordField.setName("resenhajPasswordField"); // NOI18N

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        tipoUserjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comum", "usuário ADM", "Administrador" }));
        tipoUserjComboBox.setName("tipoUserjComboBox"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(codigojSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(122, 122, 122))
                                        .addComponent(funcionariojTextField)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(enderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel17))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(numerojTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                        .addComponent(jLabel6))))
                            .addGap(28, 28, 28))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(complementojTextField)
                                .addComponent(jLabel9)
                                .addComponent(usuariojTextField))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel14)
                                .addComponent(senhajPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ufjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(252, 252, 252)))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bairrojTextField)
                        .addComponent(cpfjFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(telefonejFormattedTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(resenhajPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tipoUserjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(rgjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addComponent(cidadejTextField)))
                        .addComponent(cargojTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(213, 213, 213))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {complementojTextField, enderecojTextField});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {resenhajPasswordField, senhajPasswordField});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigojSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(funcionariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(complementojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ufjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhajPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resenhajPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rgjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cargojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoUserjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, 0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairjButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_sairjButtonActionPerformed

    private void novojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novojButtonActionPerformed
        // TODO add your handling code here:
        novojButton.setEnabled(false);
        alterarjButton.setEnabled(false);
        editarjButton.setEnabled(false);
        excluirjButton.setEnabled(false);
        buscarjButton.setEnabled(true);
        salvarjButton.setEnabled(true);
        codigojSpinner.setEnabled(false);
        funcionariojTextField.grabFocus();
        
        
        try {
            conexao.con.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(jFFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }

        Funcoes.limpaCampos(jPanel1);
        funcionariojTextField.setText("");
        cpfjFormattedTextField.setText("");
        rgjTextField.setText("");
        enderecojTextField.setText("");
        numerojTextField.setText("");
        bairrojTextField.setText("");
        cidadejTextField.setText("");
        complementojTextField.setText("");
        ufjComboBox.setSelectedItem("AC");
        telefonejFormattedTextField.setText("");
        cargojTextField.setText("");
        usuariojTextField.setText("");
        senhajPasswordField.setText("");
        resenhajPasswordField.setText("");
        tipoUserjComboBox.setSelectedItem("Comum");   

    }//GEN-LAST:event_novojButtonActionPerformed

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
        // TODO add your handling code here:

        if (funcionariojTextField.getText().equals("") || enderecojTextField.getText().equals("") ||
             numerojTextField.getText().equals("") || bairrojTextField.getText().equals("")){

            JOptionPane.showMessageDialog(null, "Preencha todos os campos.", "ATENÇÃO", JOptionPane.INFORMATION_MESSAGE);
        }else{






        salvarjButton.setEnabled(false);
        alterarjButton.setEnabled(false);
        excluirjButton.setEnabled(false);
        novojButton.setEnabled(true);
        editarjButton.setEnabled(true);


        Funcionarios oFuncionario = new Funcionarios();
        oFuncionario.setFuncionario(funcionariojTextField.getText());
        oFuncionario.setCpf(cpfjFormattedTextField.getText());
        oFuncionario.setRg(rgjTextField.getText());
        oFuncionario.setEndereco(enderecojTextField.getText());
        oFuncionario.setNumero(numerojTextField.getText());
        oFuncionario.setBairro(bairrojTextField.getText());
        oFuncionario.setCidade(cidadejTextField.getText());
        oFuncionario.setComplemento(complementojTextField.getText());
        oFuncionario.setUf((String) ufjComboBox.getSelectedItem());
        oFuncionario.setTelefone(telefonejFormattedTextField.getText());
        oFuncionario.setCargo(cargojTextField.getText());
        oFuncionario.setUsuario(usuariojTextField.getText());
        String senha = new String(senhajPasswordField.getPassword());
        oFuncionario.setSenha(senha);
        String resenha = new String(resenhajPasswordField.getPassword());
        oFuncionario.setResenha(resenha);
        oFuncionario.setTipoUser((String) tipoUserjComboBox.getSelectedItem());
        oFuncionario.setCadastrar(conexao);
        try {
            conexao.con.commit();
            conexao.con.setAutoCommit(true);
        } catch (SQLException ex) {
            Logger.getLogger(jFFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            getGradeSituacao();
        } catch (ParseException ex) {
            Logger.getLogger(jFFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }


            

                Funcoes.limpaCampos(jPanel1);
        funcionariojTextField.setText("");
        cpfjFormattedTextField.setText("");
        rgjTextField.setText("");
        enderecojTextField.setText("");
        numerojTextField.setText("");
        bairrojTextField.setText("");
        cidadejTextField.setText("");
        complementojTextField.setText("");
        ufjComboBox.setSelectedItem("AC");
        telefonejFormattedTextField.setText("");
        cargojTextField.setText("");
        usuariojTextField.setText("");
        senhajPasswordField.setText("");
        resenhajPasswordField.setText("");
        tipoUserjComboBox.setSelectedItem("Comum");
        }



    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        novojButton.setEnabled(true);
        alterarjButton.setEnabled(false);
        editarjButton.setEnabled(true);
        excluirjButton.setEnabled(false);
        buscarjButton.setEnabled(true);
        salvarjButton.setEnabled(false);
        funcionariojTextField.grabFocus();


        conexao.conecta();
        buscarjButtonActionPerformed(null);
     
    }//GEN-LAST:event_formWindowOpened

    private void buscarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarjButtonActionPerformed
        // TODO add your handling code here:
        
        try {
            
            getGradeSituacao();
        } catch (ParseException ex) {
            Logger.getLogger(jFFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        // TODO add your handling code here:
        novojButton.setEnabled(false);
        salvarjButton.setEnabled(false);
        editarjButton.setEnabled(false);
        alterarjButton.setEnabled(true);
        excluirjButton.setEnabled(true);
        try {
            conexao.con.setAutoCommit(false);
        } catch (SQLException ex) {
            Logger.getLogger(jFClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void alterarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarjButtonActionPerformed
        // TODO add your handling code here:

        alterarjButton.setEnabled(false);
        editarjButton.setEnabled(true);
        excluirjButton.setEnabled(false);
        novojButton.setEnabled(true);
        
        int codFunc = 0;
        codFunc = Integer.parseInt(gradeFuncjTable.getValueAt(gradeFuncjTable.getSelectedRow(), 0).toString());
        
        Funcionarios oFuncionario = new Funcionarios();
        oFuncionario.setCodFuncionario(codFunc);
        oFuncionario.setFuncionario(funcionariojTextField.getText());
        oFuncionario.setCpf(cpfjFormattedTextField.getText());
        oFuncionario.setRg(rgjTextField.getText());
        oFuncionario.setEndereco(enderecojTextField.getText());
        oFuncionario.setNumero(numerojTextField.getText());
        oFuncionario.setBairro(bairrojTextField.getText());
        oFuncionario.setCidade(cidadejTextField.getText());
        oFuncionario.setComplemento(complementojTextField.getText());
        oFuncionario.setUf((String) ufjComboBox.getSelectedItem());
        oFuncionario.setTelefone(telefonejFormattedTextField.getText());
        oFuncionario.setCargo(cargojTextField.getText());
        oFuncionario.setUsuario(usuariojTextField.getText());
        String senha = new String(senhajPasswordField.getPassword());
        oFuncionario.setSenha(senha);
        String resenha = new String(resenhajPasswordField.getPassword());
        oFuncionario.setResenha(resenha);
        oFuncionario.setTipoUser((String) tipoUserjComboBox.getSelectedItem());
        oFuncionario.setAlterar(conexao);
        try {
            conexao.con.commit();
            conexao.con.setAutoCommit(true);
        } catch (SQLException ex) {
            Logger.getLogger(jFFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            getGradeSituacao();
        } catch (ParseException ex) {
            Logger.getLogger(jFFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_alterarjButtonActionPerformed

    private void excluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirjButtonActionPerformed
        // TODO add your handling code here:
   Object[] options = {"Sim", "Não"};
        int sd =
                JOptionPane.showOptionDialog(
                null,
                "Deseja realmente EXCLUIR este contato?",
                "Confirmação!",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                options,
                options[0]);

        if (sd != 0) {
            return;
        }

        alterarjButton.setEnabled(false);
        editarjButton.setEnabled(true);
        excluirjButton.setEnabled(false);
        novojButton.setEnabled(true);

         int codSituacao = 0;
        codSituacao = Integer.parseInt(gradeFuncjTable.getValueAt(gradeFuncjTable.getSelectedRow(), 0).toString());

        Funcionarios oFuncionario = new Funcionarios();
        oFuncionario.setCodFuncionario(codSituacao);
        oFuncionario.setExcluir(conexao);
        try {
            conexao.con.commit();
            conexao.con.setAutoCommit(true);
        } catch (SQLException ex) {
            Logger.getLogger(jFProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            getGradeSituacao();
        } catch (ParseException ex) {
            Logger.getLogger(jFProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }

        Funcoes.limpaCampos(jPanel1);
        funcionariojTextField.setText("");
        cpfjFormattedTextField.setText("");
        rgjTextField.setText("");
        enderecojTextField.setText("");
        numerojTextField.setText("");
        bairrojTextField.setText("");
        cidadejTextField.setText("");
        complementojTextField.setText("");
        ufjComboBox.setSelectedItem("AC");
        telefonejFormattedTextField.setText("");
        cargojTextField.setText("");
        usuariojTextField.setText("");
        senhajPasswordField.setText("");
        resenhajPasswordField.setText("");
        tipoUserjComboBox.setSelectedItem("Comum");



    }//GEN-LAST:event_excluirjButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarjButton;
    private javax.swing.JTextField bairrojTextField;
    private javax.swing.JButton buscarjButton;
    private javax.swing.JTextField cargojTextField;
    private javax.swing.JTextField cidadejTextField;
    private javax.swing.JSpinner codigojSpinner;
    private javax.swing.JTextField complementojTextField;
    private javax.swing.JFormattedTextField cpfjFormattedTextField;
    private javax.swing.JButton editarjButton;
    private javax.swing.JTextField enderecojTextField;
    private javax.swing.JButton excluirjButton;
    private javax.swing.JTextField funcionariojTextField;
    private javax.swing.JTable gradeFuncjTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton novojButton;
    private javax.swing.JTextField numerojTextField;
    private javax.swing.JPasswordField resenhajPasswordField;
    private javax.swing.JTextField rgjTextField;
    private javax.swing.JButton sairjButton;
    private javax.swing.JButton salvarjButton;
    private javax.swing.JPasswordField senhajPasswordField;
    private javax.swing.JFormattedTextField telefonejFormattedTextField;
    private javax.swing.JComboBox tipoUserjComboBox;
    private javax.swing.JComboBox ufjComboBox;
    private javax.swing.JTextField usuariojTextField;
    // End of variables declaration//GEN-END:variables

}
